CREATE DATABASE IF NOT EXISTS micall DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE micall;

DELIMITER $$
CREATE  PROCEDURE SP_DEL_EMPRESA (IN _IDEMPRESA INT)  BEGIN
	DELETE FROM EMPRESA WHERE IDEMPRESA = _IDEMPRESA;
END$$

CREATE  PROCEDURE SP_EXISTE_EMPRESA (IN _RUTEMPRESA INT)  BEGIN
	SELECT
		COUNT(IDEMPRESA) CANTIDAD
	FROM
		EMPRESA
	WHERE
		RUTEMPRESA = _RUTEMPRESA;
END$$

CREATE  PROCEDURE SP_EXISTE_PRODUCTO (IN _CODPRODUCTO VARCHAR(50), IN _IDEMPRESA INT)  BEGIN
	SELECT
		COUNT(IDPRODUCTO) CANTIDAD
	FROM
		PRODUCTO
	WHERE
		CODPRODUCTO = _CODPRODUCTO
        AND IDEMPRESA = _IDEMPRESA;
END$$

CREATE  PROCEDURE SP_EXISTE_RUT_EMPRESA (IN _RUT INT)  BEGIN
	SELECT
		COUNT(RUTEMPRESA)
	FROM
		EMPRESA
	WHERE
		RUTEMPRESA = _RUT;
END$$

CREATE  PROCEDURE SP_GET_EMPRESAS ()  BEGIN
	SELECT
		IDEMPRESA,
        RUTEMPRESA,
        DVEMPRESA,
        NOMBRE,
        DIRECCION,
        CREACION,
        ULTMODIFICACION
	FROM
		EMPRESA;
END$$

CREATE  PROCEDURE SP_GET_EMPRESA_BY_ID (IN _IDEMPRESA INT)  BEGIN
	SELECT
		IDEMPRESA,
        RUTEMPRESA,
        DVEMPRESA,
        NOMBRE,
        DIRECCION,
        CREACION,
        ULTMODIFICACION
	FROM
		EMPRESA
	WHERE
		IDEMPRESA = _IDEMPRESA;
END$$

CREATE  PROCEDURE SP_GET_EMPRESA_BY_RUT (IN _RUTEMPRESA INT)  BEGIN
	SELECT
		IDEMPRESA,
        RUTEMPRESA,
        DVEMPRESA,
        NOMBRE,
        DIRECCION,
        CREACION,
        ULTMODIFICACION
	FROM
		EMPRESA
	WHERE
		RUTEMPRESA = _RUTEMPRESA;
END$$

CREATE  PROCEDURE SP_GET_PRODUCTOS ()  BEGIN
	SELECT
		A.IDPRODUCTO,
        A.IDEMPRESA,
        A.CODPRODUCTO,
        A.DESCPRODUCTO,
        B.RUTEMPRESA,
        B.DVEMPRESA,
        B.NOMBRE
	FROM
		PRODUCTO A INNER JOIN EMPRESA B
        ON A.IDEMPRESA = B.IDEMPRESA;
END$$

CREATE  PROCEDURE SP_INS_EMPRESA (IN _RUT INT, IN _DV VARCHAR(1), IN _NOMBRE VARCHAR(60), IN _DIRECCION VARCHAR(100))  BEGIN
	INSERT INTO
		EMPRESA(
			RUTEMPRESA,
            DVEMPRESA,
            NOMBRE,
            DIRECCION,
            CREACION,
            ULTMODIFICACION)
		VALUES(
			_RUT,
            _DV,
            _NOMBRE,
            _DIRECCION,
            NOW(),
            NOW());
END$$

CREATE  PROCEDURE SP_INS_PRODUCTO (IN _IDEMPRESA INT, IN _CODPRODUCTO VARCHAR(50), IN _DESCPRODUCTO VARCHAR(100))  BEGIN
	INSERT INTO 
		PRODUCTO(
            IDEMPRESA, 
            CODPRODUCTO, 
            DESCPRODUCTO) 
		VALUES(
			_IDEMPRESA, 
            _CODPRODUCTO, 
            _DESCPRODUCTO);
END$$

CREATE  PROCEDURE SP_UPD_EMPRESA (IN _IDEMPRESAORIGEN INT, IN _RUTEMPRESA INT, IN _DVEMPRESA VARCHAR(1), IN _NOMBRE VARCHAR(60), IN _DIRECCION VARCHAR(100))  BEGIN
	UPDATE EMPRESA
    SET
		RUTEMPRESA = _RUTEMPRESA,
        DVEMPRESA = _DVEMPRESA,
        NOMBRE = _NOMBRE,
        DIRECCION = _DIRECCION,
        ULTMODIFICACION = NOW()
	WHERE
		IDEMPRESA = _IDEMPRESAORIGEN;
END$$

CREATE  PROCEDURE SP_VALIDA_USUARIO (IN _RUT INT, IN _PASSWORD VARCHAR(64))  BEGIN
	SELECT
		A.IDUSUARIO,
        A.IDEMPRESA,
        B.RUTEMPRESA,
        B.DVEMPRESA,
        B.NOMBRE EMPRESA,
        A.IDTIPOUSUARIO,
        C.DESCTIPOUSUARIO,
        A.RUTUSUARIO,
        A.DVUSUARIO,
        A.NOMUSUARIO,
        A.APPATERNO,
        A.APMATERNO,
        A.ESTADO,
        A.ULTMODIFICACION
	FROM
		USUARIO A INNER JOIN EMPRESA B
        ON A.IDEMPRESA = B.IDEMPRESA INNER JOIN TIPOUSUARIO C
        ON A.IDTIPOUSUARIO = C.IDTIPOUSUARIO
	WHERE
		A.RUTUSUARIO = _RUT
        AND A.PASSWORD = _PASSWORD;
END$$

DELIMITER ;

CREATE TABLE CAMPANA (
  IDCAMPANA INT(11) NOT NULL,
  IDPRODUCTO INT(11) NOT NULL,
  NOMCAMPANA VARCHAR(100) NOT NULL,
  CODCAMPANA VARCHAR(50) NOT NULL,
  FECHAINI DATE NOT NULL,
  FECHAFIN DATE NOT NULL,
  META INT(11) NOT NULL
);

CREATE TABLE CAMPANASUBPRODUCTO (
  IDCAMPANA INT(11) NOT NULL,
  IDSUBPRODUCTO INT(11) NOT NULL,
  MONTOMETA INT(11) DEFAULT NULL,
  CANTIDADMETA INT(11) DEFAULT NULL
);

CREATE TABLE EMPRESA (
  IDEMPRESA INT(11) NOT NULL,
  RUTEMPRESA INT(11) NOT NULL,
  DVEMPRESA VARCHAR(1) NOT NULL,
  NOMBRE VARCHAR(60) NOT NULL,
  DIRECCION VARCHAR(100) NOT NULL,
  CREACION DATETIME NOT NULL,
  ULTMODIFICACION DATETIME NOT NULL
);

INSERT INTO EMPRESA (IDEMPRESA, RUTEMPRESA, DVEMPRESA, NOMBRE, DIRECCION, CREACION, ULTMODIFICACION) VALUES
(1, 11111111, '1', 'Administración INTerna', 'Sin dirección', '2019-07-25 10:25:20', '2019-07-25 10:25:20'),
(3, 22222222, '2', 'EMPRESA 2', 'Dirección EMPRESA 2', '2019-07-25 16:15:40', '2019-07-25 16:15:40'),
(4, 33333333, '3', 'EMPRESA 3', 'Dirección EMPRESA 3', '2019-07-25 16:16:59', '2019-07-25 16:16:59'),
(5, 44444444, '4', 'EMPRESA 4', 'Dirección EMPRESA 4', '2019-07-25 16:17:10', '2019-07-25 16:17:10');

CREATE TABLE PRODUCTO (
  IDPRODUCTO INT(11) NOT NULL,
  CODPRODUCTO VARCHAR(50) NOT NULL,
  IDEMPRESA INT(11) NOT NULL,
  DESCPRODUCTO VARCHAR(100) NOT NULL
);

INSERT INTO PRODUCTO (IDPRODUCTO, CODPRODUCTO, IDEMPRESA, DESCPRODUCTO) VALUES
(1, 'SAV', 3, 'Super Avance'),
(2, 'CC', 3, 'Crédito en cuotas'),
(3, 'SAV', 4, 'Super Avance'),
(4, 'AVE', 4, 'Avance Efectivo'),
(5, 'CCC', 3, 'Crédito en cuantas cuotas'),
(6, 'CC', 4, 'Crédito en cuotas');

CREATE TABLE RUTERO (
  IDCAMPANA INT(11) NOT NULL,
  RUT INT(11) NOT NULL,
  DV VARCHAR(1) NOT NULL,
  NOMBRES VARCHAR(30) NOT NULL,
  APELLIDOS VARCHAR(30) NOT NULL,
  GENERO VARCHAR(1) DEFAULT NULL,
  FECHANAC DATE DEFAULT NULL,
  DIRECCION VARCHAR(100) DEFAULT NULL,
  COMUNA VARCHAR(50) DEFAULT NULL,
  REGION VARCHAR(50) DEFAULT NULL,
  CODIGOPOSTAL INT(11) DEFAULT NULL,
  EMAIL VARCHAR(70) DEFAULT NULL,
  MONTOAPROBADO INT(11) NOT NULL,
  FONO1 INT(11) NOT NULL,
  FONO2 INT(11) DEFAULT NULL,
  FONO3 INT(11) DEFAULT NULL
);

CREATE TABLE SIMULACION (
  IDSIMULACION INT(11) NOT NULL,
  IDPRODUCTO INT(11) NOT NULL,
  FECHASIMULACION DATETIME NOT NULL,
  RUTVENDEDOR INT(11) NOT NULL,
  DVVENDEDOR VARCHAR(1) NOT NULL,
  RUTCLIENTE INT(11) NOT NULL,
  DVCLIENTE VARCHAR(1) NOT NULL,
  MONTO INT(11) NOT NULL,
  CUOTAS INT(11) NOT NULL,
  VALORCUOTA INT(11) NOT NULL,
  TASAINTERES decimal(5,2) NOT NULL,
  TASAANUAL decimal(5,2) NOT NULL,
  CAE decimal(5,2) NOT NULL,
  VENCIMIENTO DATE NOT NULL,
  COSTOTOTAL INT(11) NOT NULL,
  COMISION INT(11) NOT NULL
);

CREATE TABLE SIMULACIONSUBPRODUCTO (
  IDSIMULACION INT(11) NOT NULL,
  IDSUBPRODUCTO INT(11) NOT NULL
);

CREATE TABLE SUBPRODUCTO (
  IDSUBPRODUCTO INT(11) NOT NULL,
  IDEMPRESA INT(11) NOT NULL,
  CODSUBPRODUCTO VARCHAR(50) NOT NULL,
  DESCSUBPRODUCTO VARCHAR(100) NOT NULL,
  PRIMA decimal(5,2) NOT NULL
);

CREATE TABLE TIPOUSUARIO (
  IDTIPOUSUARIO INT(11) NOT NULL,
  DESCTIPOUSUARIO VARCHAR(50) NOT NULL
);

INSERT INTO TIPOUSUARIO (IDTIPOUSUARIO, DESCTIPOUSUARIO) VALUES
(1, 'Administrador');

CREATE TABLE USUARIO (
  IDUSUARIO INT(11) NOT NULL,
  IDEMPRESA INT(11) NOT NULL,
  IDTIPOUSUARIO INT(11) NOT NULL,
  RUTUSUARIO INT(11) NOT NULL,
  DVUSUARIO VARCHAR(1) NOT NULL,
  NOMUSUARIO VARCHAR(60) NOT NULL,
  APPATERNO VARCHAR(50) NOT NULL,
  APMATERNO VARCHAR(50) NOT NULL,
  ESTADO INT(11) NOT NULL,
  ULTMODIFICACION DATETIME NOT NULL,
  PASSWORD VARCHAR(64) NOT NULL
);

INSERT INTO USUARIO (IDUSUARIO, IDEMPRESA, IDTIPOUSUARIO, RUTUSUARIO, DVUSUARIO, NOMUSUARIO, APPATERNO, APMATERNO, ESTADO, ULTMODIFICACION, PASSWORD) VALUES
(1, 1, 1, 16355662, '6', 'Jorge', 'Silva', 'Borda', 1, '2019-07-25 10:27:50', '06e35faa71f61cbabf8b65bace7b1a38');


ALTER TABLE CAMPANA
  ADD PRIMARY KEY (IDCAMPANA),
  ADD KEY FK_RELATIONSHIP_6 (IDPRODUCTO);

ALTER TABLE CAMPANASUBPRODUCTO
  ADD KEY FK_RELATIONSHIP_7 (IDCAMPANA),
  ADD KEY FK_RELATIONSHIP_8 (IDSUBPRODUCTO);

ALTER TABLE EMPRESA
  ADD PRIMARY KEY (IDEMPRESA);

ALTER TABLE PRODUCTO
  ADD PRIMARY KEY (IDPRODUCTO),
  ADD KEY FK_RELATIONSHIP_5 (IDEMPRESA);

ALTER TABLE RUTERO
  ADD KEY FK_RELATIONSHIP_12 (IDCAMPANA);

ALTER TABLE SIMULACION
  ADD PRIMARY KEY (IDSIMULACION),
  ADD KEY FK_RELATIONSHIP_9 (IDPRODUCTO);

ALTER TABLE SIMULACIONSUBPRODUCTO
  ADD KEY FK_RELATIONSHIP_10 (IDSIMULACION),
  ADD KEY FK_RELATIONSHIP_11 (IDSUBPRODUCTO);

ALTER TABLE SUBPRODUCTO
  ADD PRIMARY KEY (IDSUBPRODUCTO),
  ADD KEY FK_RELATIONSHIP_4 (IDEMPRESA);

ALTER TABLE TIPOUSUARIO
  ADD PRIMARY KEY (IDTIPOUSUARIO);

ALTER TABLE USUARIO
  ADD PRIMARY KEY (IDUSUARIO),
  ADD KEY FK_RELATIONSHIP_1 (IDTIPOUSUARIO),
  ADD KEY FK_RELATIONSHIP_2 (IDEMPRESA);


ALTER TABLE CAMPANA
  MODIFY IDCAMPANA INT(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE EMPRESA
  MODIFY IDEMPRESA INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

ALTER TABLE PRODUCTO
  MODIFY IDPRODUCTO INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

ALTER TABLE SIMULACION
  MODIFY IDSIMULACION INT(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE SUBPRODUCTO
  MODIFY IDSUBPRODUCTO INT(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE TIPOUSUARIO
  MODIFY IDTIPOUSUARIO INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

ALTER TABLE USUARIO
  MODIFY IDUSUARIO INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;
